
  
name: BabyCoin Electron Wallet Build
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
              os: [macos-latest]

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v1

            - name: Install node
              uses: actions/setup-node@v1
              with:
                node-version: "11.9.0"

            - name: Install dependencies
              run: npm install -f
              
            - name: Publish mac binaries
              if: runner.os == 'macOS'
              run: npm run build
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                CSC_LINK: ${{ secrets.MAC_CERTIFICATE }}
                CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
                ELECTRON_WALLET_APPLE_ID: ${{ secrets.ELECTRON_WALLET_APPLE_ID }}
                ELECTRON_WALLET_PASSWORD: ${{ secrets.ELECTRON_WALLET_PASSWORD }}
                ELECTRON_WALLET_TEAM_ID: ${{ secrets.ELECTRON_WALLET_TEAM_ID }}

            - name: Remove un-needed artifacts
              run: rm -r -- ./*/
              shell: bash
              working-directory: ./dist/electron-mat/Packaged 

            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                name: ${{ runner.OS }}
                path: dist/electron-mat/Packaged
